#!/usr/bin/env bash
# A  script that  runs nginx server with nginx user and fixes encountered bugs

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sudo --user nginx service nginx start
